### ISSUE TITLE
What is the problem with directories in mp_filelist?

### ISSUE THREAD

**Issue by jack-hamilton-kpdor** [macropeople/macrocore#13]
There's a comment in the macro that detection of directories is not reliable under Unix.  I use a similar but not identical program, and haven't seen a problem.  What are the circumstances where you've seen this happen?

My macro is attached.  It seems to use the same basic methods as your macro.
[files.txt](https://github.com/macropeople/macrocore/files/4477357/files.txt)

**Comment by allanbowe** [comment]
If you use SAS to scan a Unix filesystem you will fall down a black hole (figuratively, literally?) if / when you hit a [named pipe](https://en.wikipedia.org/wiki/Named_pipe).

If you know of a way to detect those we'd gladly accept a PR!

**Comment by jack-hamilton-kpdor** [comment]
Ah.  I've never used one, so I haven't run into that problem.

**Comment by allanbowe** [comment]
I've only seen it once, but the impact on a SAS9 environment (hung STP sessions) could bring down an environment, hence a big fat 'use with care' label.
