### ISSUE TITLE
Include date modified in result set for mp_dirlist()

### ISSUE THREAD

**Issue by cj13579** [macropeople/macrocore#14]
I find the `mp_dirlist()` macro very useful for listing directories with lost of files and folders and I can use the resulting dataset for many things. What I can't do at the moment is sort the output by date modified. I've seen [this example](https://documentation.sas.com/?docsetId=mcrolref&docsetTarget=n0js70lrkxo6uvn1fl4a5aafnlgt.htm&docsetVersion=9.4&locale=en) on the SAS docs site which could be a way of implementing this.

Thoughts?

**Comment by allanbowe** [comment]
Good feedback, thanks Chris.  I added an extra option to enhance the output table with file / folder properties, does it look ok?

https://github.com/macropeople/macrocore/pull/15
