### ISSUE TITLE
tabs not spaces for getstpcode

### ISSUE THREAD

**Issue by mortie23** [macropeople/macrocore#21]
the code base I have uses tabs for indentation, not spaces and the code didn't work with the includsion of tabs in the escaped characters i.e. 
```sas
when ('&#x09;') rec='09'x;
```

**Comment by allanbowe** [comment]
Hi @mortie23  - this repo is actually deprecated and moved here:  github.com/sasjs/core

We'll apply your fix, thanks for the contribution!

**Comment by allanbowe** [comment]
https://github.com/sasjs/core/commit/578ef26cd5b7e68989b216aaffae6bdf83eabde5
